server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    druid:

      #初始化大小
      initial-size: 5
      min-idle: 5
      #最大连接数
      max-active: 20
      #获取连接最大等待时间
      max-wait: 60000
      #间隔多久检测一次需求关闭的空闲连接 毫秒
      time-between-eviction-runs-millis: 6000
      #连接在连接池中最小生存时间 毫秒
      min-evictable-idle-time-millis: 300000

mybatis-plus:
  type-aliases-package: com.lsl.exam.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
